work around a bug in struct.pack() (CNY-1746)
$ python -c 'import struct; print repr(struct.pack("H", 65536))'
Traceback (most recent call last):
  File "<string>", line 1, in ?
struct.error: short format requires 0<=number<=USHRT_MAX
$ python -c 'import struct; print repr(struct.pack("!H", 65536))'
'\x00\x00'

    * A bug in Python can cause overflow conditions when storing
      unsigned short integers in StreamCollection objects.  Manual
      overflow checking has been added to avoid corrupting frozen
      streams. (CNY-1746)